DROP DATABASE IF EXISTS appXamarin;
CREATE DATABASE appXamarin;

USE appXamarin;

CREATE TABLE codigo(
idCodigo INT AUTO_INCREMENT PRIMARY KEY,
numCodigo VARCHAR(10) NOT NULL UNIQUE 
)ENGINE=InnoDB;

CREATE TABLE usuario(
idUsuario INT AUTO_INCREMENT PRIMARY KEY,
nombres VARCHAR(20) NOT NULL,
apellidos VARCHAR(20) NOT NULL,
telefono INT NOT NULL UNIQUE
)ENGINE=InnoDB;


CREATE TABLE ubicacion(
idUbicacion INT AUTO_INCREMENT PRIMARY KEY,
latitud VARCHAR(15),
longitud VARCHAR(15)
)ENGINE=InnoDB;


CREATE TABLE alerta(
idAlerta INT AUTO_INCREMENT PRIMARY KEY,
idUsuario INT NOT NULL,
idUbicacion INT NOT NULL,
mensaje text NULL,
FOREIGN KEY (idUsuario) REFERENCES usuario(idUsuario) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (idUbicacion) REFERENCES ubicacion(idUbicacion) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB;


CREATE TABLE circuloFamiliar(
idCirculoFamiliar INT AUTO_INCREMENT PRIMARY KEY,
idUsuario INT NOT NULL,
idCodigo INT NOT NULL,
FOREIGN KEY (idUsuario) REFERENCES usuario(idUsuario) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (idCodigo) REFERENCES codigo(idCodigo) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB;


CREATE TABLE historial(
idHistorial INT AUTO_INCREMENT PRIMARY KEY,
idAlerta INT NOT NULL ,
fecha TIMESTAMP NOT NULL,
FOREIGN KEY (idAlerta) REFERENCES alerta(idAlerta) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB;
